### ISSUE TITLE
img upload dummy

### ISSUE THREAD

**Issue by jutanke** [jutanke/pak#1]
![milk](https://user-images.githubusercontent.com/831215/32673460-9057f8ac-c64f-11e7-97e0-672eef1fe75d.png)

**Comment by justayak** [comment]
![pak_lspe](https://user-images.githubusercontent.com/831215/32917435-77d235ac-cb1f-11e7-957e-8fcd8301e271.png)

**Comment by justayak** [comment]
![duke](https://user-images.githubusercontent.com/831215/33133206-5fd89e88-cf9c-11e7-930c-65ef51ae061a.png)

**Comment by justayak** [comment]
![hand_dataset](https://user-images.githubusercontent.com/831215/33312758-13f0f7f4-d429-11e7-9561-3cebf8832548.png)

**Comment by justayak** [comment]
![egohands](https://user-images.githubusercontent.com/831215/33382371-da8a84a0-d520-11e7-8e87-95c5aba8e814.png)

**Comment by justayak** [comment]
![marconi_img](https://user-images.githubusercontent.com/831215/36093006-902b7ac8-0fe9-11e8-92a6-c5507f454fa1.png)

**Comment by justayak** [comment]
![umpm](https://user-images.githubusercontent.com/831215/37305298-46b724c6-2634-11e8-81bd-68fe2ba4aada.png)
